parserOptions:
  sourceType: module
  parserOptions:
    jsx: true

env:
  browser: true

extends:
  - "plugin:react/recommended"

settings:
  react:
    pragma: h
    fragment: Fragment
    version: "16.0"

rules:
  react/prop-types: 0
